import type { Request, Response } from "express";
import { load } from "cheerio";
import { getEvents } from "./events";
import { fetchHackClubPreview, fetchUnstopPreview, assertSafePublicUrl } from "./urlApi";
import { SUPPORTED_SITES } from "./supportedSites";
import { deriveOpportunityStatus, isDefaultUpcoming, opportunityDataQuality } from "./opportunityTrust";

const SOURCE_TIMEOUT_MS = 60000;
let cachedOpportunities: { expiresAt: number; payload: unknown } | null = null;
export function resetOpportunitiesCache() { cachedOpportunities = null; }
function withSourceTimeout<T>(promise: Promise<T>, timeoutMs = SOURCE_TIMEOUT_MS) { return Promise.race([promise, new Promise<T>((_, reject) => setTimeout(() => reject(new Error("Source request timed out")), timeoutMs))]); }

type Opportunity = {
  id: string; source: string; sourceId: string; title: string; organizer: string; type: string;
  description: string; startDate: string; endDate: string; deadline: string; url: string; eventUrl: string; registrationUrl: string; sourcePageUrl: string;
  cost: "free" | "paid" | "unknown"; mode: "online" | "offline" | "hybrid" | "unknown";
  country: string; state: string; district: string; location: string; domain: string;
  skills: string; tags: string; eligibility: string; prizes: string; prizePool: string; participants: string; featured: string; status: string; dataQuality: "verified" | "partial" | "directory-only"; logo: string; fetchedAt: string;
};

function clean(value: unknown): string { if (value == null) return ""; if (typeof value === "object") { const record = value as Record<string, unknown>; const preferred = record.name ?? record.label ?? record.title ?? record.value ?? record.city ?? record.state ?? record.country; if (preferred != null && preferred !== value) return clean(preferred); return Object.values(record).filter(item => typeof item === "string" || typeof item === "number").map(item => String(item)).join(", "); } const text = String(value).replace(/\s+/g, " ").trim(); return text === "[object Object]" ? "" : text; }
export function classifySourceFetchError(message: string) { return /HTTP (403|405)/.test(message) ? "blocked" : "unavailable" as const; }
function classifyCost(text: string): Opportunity["cost"] { const value = text.toLowerCase(); if (/free|no fee|₹\s*0|\$\s*0/.test(value)) return "free"; if (/fee|paid|₹|\$\s*\d/.test(value)) return "paid"; return "unknown"; }
function classifyMode(text: string): Opportunity["mode"] { const value = text.toLowerCase(); if (/hybrid/.test(value)) return "hybrid"; if (/online|virtual|remote|work from home|digital/.test(value)) return "online"; if (/offline|in.?person|on.?site|campus/.test(value)) return "offline"; return "unknown"; }
function domainFor(text: string) { const value = text.toLowerCase(); const domains = ["artificial intelligence", "ai", "machine learning", "web3", "blockchain", "cyber security", "data science", "software development", "robotics", "design", "health", "fintech", "gaming", "education"]; return domains.filter(domain => value.includes(domain)).slice(0, 4).join(", ") || "General"; }
export function ensureUniqueOpportunityIds<T extends { id: string }>(records: T[]) { const counts = new Map<string, number>(); return records.map(record => { const count = (counts.get(record.id) || 0) + 1; counts.set(record.id, count); return count === 1 ? record : { ...record, id: `${record.id}#${count}` }; }); }
export function dedupeByCanonicalUrl<T extends { url: string }>(records: T[]) { const seen = new Set<string>(); return records.filter(record => { try { const url = new URL(record.url); url.hash = ""; url.search = ""; if (url.pathname !== "/") url.pathname = url.pathname.replace(/\/+$/, "") || "/"; const canonical = url.toString(); if (seen.has(canonical)) return false; seen.add(canonical); return true; } catch { return false; } }); }

export function normalizeOpportunity(source: string, sourceId: string, raw: Record<string, unknown>): Opportunity {
  const title = clean(raw.title || raw.name || raw.eventName || raw.challenge || "Untitled opportunity");
  const description = clean(raw.description || raw.details || raw.eventDescription || raw.summary);
  const location = clean(raw.location || raw.city || raw.address);
  const context = [title, description, location, raw.type, raw.mode, raw.tags, raw.skills].map(clean).join(" ");
  const registrationUrl = clean(raw.registrationUrl);
  const eventUrl = clean(raw.eventUrl || raw.detailUrl || raw.url);
  const sourcePageUrl = clean(raw.sourcePageUrl || raw.sourceUrl || raw.listingUrl || raw.directoryUrl);
  const startDate = clean(raw.startDate || raw.start || raw.date);
  const endDate = clean(raw.endDate || raw.end);
  const deadline = clean(raw.deadline || raw.registrationDeadline || raw.closeDate);
  const trustInput = { registrationUrl, eventUrl, sourcePageUrl, deadline, startDate, endDate, mode: classifyMode(context), location, eligibility: clean(raw.eligibility || raw.eligibilityCriteria || raw.audience) };
  return { id: `${sourceId}:${clean(raw.id || eventUrl || registrationUrl || title)}`, source, sourceId, title, organizer: clean(raw.organizer || raw.organisation || raw.host || raw.company || "Organizer not listed"), type: clean(raw.type || raw.category || "Opportunity"), description, startDate, endDate, deadline, url: registrationUrl || eventUrl || sourcePageUrl, eventUrl, registrationUrl, sourcePageUrl, cost: classifyCost(context), mode: classifyMode(context), country: clean(raw.country), state: clean(raw.state), district: clean(raw.district || raw.city), location, domain: domainFor(context), skills: clean(raw.skills), tags: clean(raw.tags || raw.labels || raw.keywords), eligibility: trustInput.eligibility, prizes: clean(raw.prizes || raw.reward), prizePool: clean(raw.prizePool || raw.prizes || raw.reward), participants: clean(raw.participants || raw.participantCount || raw.attendees), featured: clean(raw.featured || raw.isFeatured), status: deriveOpportunityStatus(trustInput), dataQuality: opportunityDataQuality(trustInput), logo: clean(raw.logo || raw.image), fetchedAt: new Date().toISOString() };
}

export function isDevpostEventUrl(value: string) { try { const url = new URL(value); return url.protocol === "https:" && /^[a-z0-9-]+\.devpost\.com$/.test(url.hostname) && url.pathname === "/"; } catch { return false; } }

function parseDevpostCardLine(line: string) { const urlMatch = line.match(/\((https?:\/\/[^)]+\.devpost\.com\/[^)]*)\)/); const eventUrl = urlMatch?.[1]?.split("?")[0] || ""; if (!eventUrl || !isDevpostEventUrl(eventUrl)) return null; const imageMatch = line.match(/\((https?:\/\/[^)]+)\)\s+#####\s+/); const start = line.indexOf("##### "); if (start < 0) { const bareTitle = line.match(/^\[([^\]]+)\]/)?.[1] || "Devpost hackathon"; return { id: eventUrl, title: bareTitle, description: "", url: eventUrl, logo: "", prizes: "", prizePool: "", participants: "", deadline: "", startDate: "", mode: "", location: "", type: "Hackathon", status: "upcoming", featured: false, tags: "artificial intelligence", eligibility: "" }; } const close = line.lastIndexOf("]("); const body = line.slice(start + 6, close).replace(/\s+/g, " ").trim(); const marker = body.search(/(?:\$|₹|Non-monetary prizes|\d[\d,]* participants|Deadline:|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{1,2})/); const titleDescription = marker > 0 ? body.slice(0, marker).trim() : body; const namedEvent = titleDescription.match(/^(.+?\b(?:Hackathon|Challenge|Competition)\b)/i); const sentence = titleDescription.search(/\.\s/); const title = (namedEvent?.[1] || (sentence > 20 ? titleDescription.slice(0, sentence + 1) : titleDescription)).trim(); const description = titleDescription.slice(title.length).trim(); const prize = body.match(/(?:\$|₹)\s*[\d,]+(?:\.\d+)?(?:\s*[KMB])? in prizes|Non-monetary prizes/i)?.[0] || ""; const participants = body.match(/[\d,]+ participants/i)?.[0]?.replace(/ participants/i, "") || ""; const deadline = body.match(/Deadline: ([A-Z][a-z]{2} \d{1,2}, \d{4})/i)?.[1] || ""; const dateRange = body.match(/(?:[A-Z][a-z]{2} \d{1,2}(?: - [A-Z][a-z]{2} \d{1,2})?, \d{4})/)?.[0] || ""; const mode = /\bOnline\b/i.test(body) ? "Online" : /\bIn-person\b/i.test(body) ? "In-person" : ""; const location = body.match(/(?:Online|In-person)\s+([^\[]+?)(?=\]?$)/i)?.[1]?.trim() || ""; return { id: eventUrl, title: title || new URL(eventUrl).hostname.split(".")[0], description, url: eventUrl, logo: imageMatch?.[1] || "", prizes: prize, prizePool: prize, participants, deadline, startDate: dateRange, mode, location, type: "Hackathon", status: "upcoming", featured: /Featured/i.test(body), tags: "artificial intelligence", eligibility: "" }; }

export function parseDevpostMarkdown(markdown: string) { const records = markdown.split(/\n+/).map(parseDevpostCardLine).filter((record): record is NonNullable<ReturnType<typeof parseDevpostCardLine>> => Boolean(record)); return ensureUniqueOpportunityIds(records); }

export function devpostOrganizerFromUrl(value: string) { try { const slug = new URL(value).hostname.replace(/\.devpost\.com$/, ""); const ignored = new Set(["ai", "api", "app", "challenge", "competition", "hack", "hackathon", "hacks", "v", "2026", "2027"]); const parts = slug.split(/[-_]+/).filter(part => part && !ignored.has(part.toLowerCase())); const brands: Record<string, string> = { youcam: "YouCam", xprize: "XPRIZE", aws: "AWS", ibm: "IBM", gcp: "Google Cloud", google: "Google", meta: "Meta" }; return parts.slice(0, 3).map(part => brands[part.toLowerCase()] || (part.length <= 4 ? part.toUpperCase() : part.charAt(0).toUpperCase() + part.slice(1))).join(" "); } catch { return ""; } }

export function extractDevpostDetailFields(markdown: string, url = "") { const text = markdown.replace(/\s+/g, " ").trim(); const organizer = text.match(/(?:Join|from|with) ([A-Z][A-Za-z0-9& .-]{2,60}?)(?= and |, |\. | to | for | the )/)?.[1]?.trim() || devpostOrganizerFromUrl(url); const eligibility = text.match(/Eligibility\s*:?\s*([^\n]{0,280})/i)?.[1]?.trim() || ""; return { organizer, eligibility }; }

async function enrichDevpostRecord(record: NonNullable<ReturnType<typeof parseDevpostCardLine>>) { try { const host = new URL(record.url).hostname; const response = await fetch(`https://r.jina.ai/http://${host}/`, { headers: { accept: "text/markdown", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(4000) }); if (!response.ok) return record; const fields = extractDevpostDetailFields(await response.text(), record.url); return { ...record, organizer: fields.organizer, eligibility: fields.eligibility }; } catch { return record; } }

async function fetchDevpostPreview() { const response = await fetch("https://r.jina.ai/http://devpost.com/c/artificial-intelligence", { headers: { accept: "text/markdown", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const markdown = await response.text(); const records = parseDevpostMarkdown(markdown).slice(0, 40); return { records: await Promise.all(records.map(enrichDevpostRecord)) }; }

export const KAGGLE_PAGE_SIZE = 1000;
export const KAGGLE_PAGE_COUNT = 1;
const KAGGLE_LIST_URL = `https://www.kaggle.com/api/i/competitions.CompetitionService/ListCompetitions?pageSize=${KAGGLE_PAGE_SIZE}&pageToken=`;
function kaggleValue(value: unknown): string { if (Array.isArray(value)) return value.map(kaggleValue).filter(Boolean).join(", "); return clean(value); }
function kaggleReward(value: unknown) { if (!value || typeof value !== "object") return ""; const reward = value as Record<string, unknown>; const amount = Number(reward.quantity); const currency = clean(reward.id); if (Number.isFinite(amount) && amount > 0) return `${currency === "USD" ? "$" : currency ? `${currency} ` : ""}${amount.toLocaleString("en-US")}`; return clean(reward.clarification); }
function kaggleOrganizer(raw: Record<string, unknown>) { const organization = raw.organization; if (organization && typeof organization === "object") return clean(raw.hostName || (organization as Record<string, unknown>).displayName || (organization as Record<string, unknown>).name); return clean(raw.hostName); }
export function parseKaggleCompetitions(payload: unknown, now = Date.now()) { const source = payload && typeof payload === "object" ? payload as Record<string, unknown> : {}; const competitions: unknown[] = Array.isArray(source.competitions) ? source.competitions : []; const images: Record<string, unknown> = source.thumbnailImageUrls && typeof source.thumbnailImageUrls === "object" ? source.thumbnailImageUrls as Record<string, unknown> : {}; return ensureUniqueOpportunityIds(competitions.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object")).filter(item => { const deadline = Date.parse(clean(item.deadline)); return Number.isFinite(deadline) && deadline > now && clean(item.competitionName); }).map(item => { const reward = kaggleReward(item.reward); const tags = kaggleValue(item.categories); const isHackathon = Boolean(item.hackathon); return { id: clean(item.id || item.competitionName), title: clean(item.title || item.competitionName), description: clean(item.briefDescription), url: `https://www.kaggle.com/competitions/${encodeURIComponent(clean(item.competitionName))}`, organizer: kaggleOrganizer(item) || "Kaggle", type: isHackathon ? "Hackathon" : "Competition", startDate: clean(item.dateEnabled), deadline: clean(item.deadline), prizePool: reward, prizes: reward, participants: clean(item.totalTeams || item.teamCount || item.totalCompetitors), tags, skills: tags, featured: clean(item.competitionHostSegmentId) === "1", status: "open", mode: "Online", eligibility: "See competition rules on Kaggle", logo: clean(images[clean(item.id)]) }; })); }
async function fetchKagglePreview() { const tokens = Array.from({ length: KAGGLE_PAGE_COUNT }, (_, index) => String(index * KAGGLE_PAGE_SIZE)); const pages = await Promise.all(tokens.map(async token => { const response = await fetch(`${KAGGLE_LIST_URL}${token}`, { headers: { accept: "application/json", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(45000) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.json() as Record<string, unknown>; })); const competitions = pages.flatMap(page => Array.isArray(page.competitions) ? page.competitions : []); const thumbnailImageUrls = Object.assign({}, ...pages.map(page => page.thumbnailImageUrls && typeof page.thumbnailImageUrls === "object" ? page.thumbnailImageUrls : {})); return { records: parseKaggleCompetitions({ competitions, thumbnailImageUrls }) }; }

const HACK2SKILL_API = "https://hack2skill.com/api/v1/innovator/public/event/public-list";
const HACK2SKILL_PAGE_SIZE = 51;
const HACK2SKILL_MAX_PAGES = 4;
export const HACK2SKILL_PAGE_SIZE_CONFIG = { pageSize: HACK2SKILL_PAGE_SIZE, maxPages: HACK2SKILL_MAX_PAGES };
function parseHack2SkillEvents(payload: unknown, now = Date.now()) {
  const source = payload && typeof payload === "object" ? payload as Record<string, unknown> : {};
  const rows = Array.isArray(source.data) ? source.data.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object")) : [];
  return rows.filter(row => { const deadline = Date.parse(clean(row.registrationEnd)); return Boolean(clean(row.eventUrl) && clean(row.title) && Number.isFinite(deadline) && deadline > now); }).map(row => {
    const ticket = clean(row.ticket) || "FREE";
    const mode = clean(row.mode).replace(/_/g, " ").toLowerCase();
    const detailUrl = `https://hack2skill.com/event/${encodeURIComponent(clean(row.eventUrl))}`;
    return { id: clean(row._id || row.eventUrl), title: clean(row.title), description: "", url: detailUrl, organizer: "Hack2Skill", type: "Hackathon", startDate: clean(row.submissionStart || row.registrationStart), endDate: clean(row.submissionEnd), deadline: clean(row.registrationEnd), mode, location: mode === "virtual" ? "" : mode === "in person" ? "In Person" : "", prizes: ticket, prizePool: ticket, tags: clean(row.flag), eligibility: clean(row.participation), logo: clean(row.thumbnail), status: "open", featured: clean(row.flag).toLowerCase() === "flagship" };
  });
}
export { parseHack2SkillEvents };
async function fetchHack2SkillPreview() {
  const now = new Date();
  const start = now.toISOString();
  const endDate = new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000).toISOString();
  const firstResponse = await fetch(`${HACK2SKILL_API}?page=1&records=${HACK2SKILL_PAGE_SIZE}&search=&start=${encodeURIComponent(start)}&end=${encodeURIComponent(endDate)}`, { headers: { accept: "application/json", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(30000) });
  if (!firstResponse.ok) throw new Error(`HTTP ${firstResponse.status}`);
  const first = await firstResponse.json() as Record<string, unknown>;
  const pages = Math.min(Math.max(Number(first.pages || 1), 1), HACK2SKILL_MAX_PAGES);
  const rest = await Promise.all(Array.from({ length: pages - 1 }, (_, index) => index + 2).map(async page => {
    const response = await fetch(`${HACK2SKILL_API}?page=${page}&records=${HACK2SKILL_PAGE_SIZE}&search=&start=${encodeURIComponent(start)}&end=${encodeURIComponent(endDate)}`, { headers: { accept: "application/json", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(30000) });
    if (!response.ok) throw new Error(`HTTP ${response.status} on page ${page}`);
    return await response.json() as Record<string, unknown>;
  }));
  return { records: ensureUniqueOpportunityIds([first, ...rest].flatMap(page => parseHack2SkillEvents(page))) };
}

const RESKILLL_DISCOVER_URL = "https://reskilll.com/discover";
const RESKILLL_MONTHS: Record<string, number> = { jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11 };
function reskillScheduleEnd(value: string) {
  const text = clean(value).replace(/\s+/g, " ");
  const crossMonth = text.match(/(\d{1,2})\s+([A-Za-z]+)\s*(?:–|-)\s*(\d{1,2})\s+([A-Za-z]+),?\s+(\d{4})/i);
  const sameMonth = text.match(/\d{1,2}\s*(?:&|and|–|-)\s*(\d{1,2})\s+([A-Za-z]+),?\s+(\d{4})/i);
  if (!crossMonth && !sameMonth) return "";
  const month = RESKILLL_MONTHS[(crossMonth?.[4] || sameMonth?.[2] || "").slice(0, 3).toLowerCase()];
  const year = Number(crossMonth?.[5] || sameMonth?.[3]); const day = Number(crossMonth?.[3] || sameMonth?.[1]);
  return Number.isFinite(year) && Number.isFinite(day) && month !== undefined ? new Date(Date.UTC(year, month, day, 23, 59, 59)).toISOString() : "";
}
export function parseReskillDiscover(html: string, now = Date.now()) {
  const $ = load(html);
  const records = $("a[target='_blank']").toArray().flatMap(anchor => {
    const card = $(anchor); const className = card.attr("class") || ""; const href = clean(card.attr("href"));
    if (!className.includes("rounded-2xl") || !className.includes("h-full") || !href || href.includes("/hack/")) return [];
    const content = card.children("div").eq(1); const title = clean(content.find("h3").first().text());
    const banner = clean(card.children("div").first().find("img").first().attr("src"));
    if (!title || !banner) return [];
    const organizerRow = content.children("div").first(); const organizer = clean(organizerRow.find("span").first().text()) || "Reskilll";
    const mode = clean(card.children("div").first().find("span").last().text());
    const tags = content.find("h3").first().next("div").find("span").map((_, tag) => clean($(tag).text())).get().filter(Boolean);
    const schedule = clean(content.find("svg.lucide-calendar").first().parent().text());
    const location = clean(content.find("svg.lucide-map-pin").first().parent().text());
    const footer = content.children("div").last(); const prize = clean(footer.find("span").first().text()).replace(/Register$/i, "").trim();
    const status = tags.find(tag => /live|registrations? open|ongoing/i.test(tag)) || schedule.match(/registrations? open|live|ongoing/i)?.[0] || "";
    const inactive = /closed|ended/i.test([schedule, ...tags].join(" ")); const endDate = reskillScheduleEnd(schedule);
    if (inactive || !status || (endDate && Date.parse(endDate) <= now)) return [];
    return [{ id: href, title, organizer, type: "Hackathon", description: "", url: href, startDate: schedule, endDate, deadline: endDate, mode, location, tags: tags.join(", "), prizes: prize, prizePool: prize, status, logo: banner, featured: /live/i.test(status) }];
  });
  return ensureUniqueOpportunityIds(records);
}
async function fetchReskillPreview() {
  const response = await fetch(RESKILLL_DISCOVER_URL, { headers: { accept: "text/html,application/xhtml+xml", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(30000) });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  return { records: parseReskillDiscover(await response.text()) };
}

const DEVFOLIO_UPCOMING_API = "https://api.devfolio.co/api/search/hackathons";
const DEVFOLIO_UPCOMING_READER_URL = "https://r.jina.ai/http://https://devfolio.co/hackathons/upcoming";
const MONTH_INDEX: Record<string, number> = { jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11 };
function devfolioOpenDate(value: string) { const match = clean(value).match(/(\d{1,2})\/(\d{1,2})\/(\d{2,4})/); if (!match) return ""; const year = Number(match[3].length === 2 ? `20${match[3]}` : match[3]); const month = Number(match[2]) - 1; const day = Number(match[1]); return Number.isFinite(year) && month >= 0 && month < 12 && day > 0 ? new Date(Date.UTC(year, month, day, 0, 0, 0)).toISOString() : ""; }
export function parseDevfolioUpcoming(markdown: string, now = Date.now()) {
  const lines = markdown.split(/\r?\n/).map(line => clean(line)); const records: Record<string, unknown>[] = [];
  for (let index = 0; index < lines.length; index += 1) {
    const match = lines[index].match(/^###\s+\[([^\]]+)\]\((https:\/\/[^)]+\.devfolio\.co\/?[^)]*)\)$/i);
    if (!match) continue;
    const window = lines.slice(index + 1, index + 20); const openLabel = window.find(line => /^Opens\s+\d{1,2}\/\d{1,2}\/\d{2,4}$/i.test(line)) || ""; const startDate = devfolioOpenDate(openLabel);
    const mode = window.find(line => /^(Online|Offline|Hybrid)$/i.test(line)) || ""; const themeIndex = window.findIndex(line => /^Theme$/i.test(line)); const theme = themeIndex >= 0 ? window.slice(themeIndex + 1).find(Boolean) || "" : "";
    if (!startDate || Date.parse(startDate) <= now) continue;
    records.push({ id: match[2], title: match[1], organizer: "Devfolio", type: "Hackathon", description: "", url: match[2], startDate: openLabel, deadline: startDate, mode, tags: [theme, "Upcoming"].filter(Boolean).join(", "), status: "Upcoming", eligibility: "See event page for registration details" });
  }
  return ensureUniqueOpportunityIds(records as Array<{ id: string }>);
}
function devfolioOpeningLabel(value: string) { const date = new Date(value); if (!Number.isFinite(date.getTime())) return ""; return `Opens ${date.toLocaleDateString("en-GB", { day: "2-digit", month: "2-digit", year: "2-digit", timeZone: "UTC" })}`; }
export function parseDevfolioUpcomingApi(payload: unknown, now = Date.now()) { const source = payload && typeof payload === "object" ? payload as Record<string, unknown> : {}; const hitsRoot = source.hits && typeof source.hits === "object" ? source.hits as Record<string, unknown> : {}; const hits = Array.isArray(hitsRoot.hits) ? hitsRoot.hits : []; const records = hits.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object")).flatMap(hit => { const raw = hit._source && typeof hit._source === "object" ? hit._source as Record<string, unknown> : {}; const settings = raw.hackathon_setting && typeof raw.hackathon_setting === "object" ? raw.hackathon_setting as Record<string, unknown> : {}; const registrationStart = clean(settings.reg_starts_at); const subdomain = clean(settings.subdomain || raw.slug); const registrationTime = Date.parse(registrationStart); if (!clean(raw.name) || !subdomain || !/^[a-z0-9-]+$/i.test(subdomain) || !Number.isFinite(registrationTime) || registrationTime <= now) return []; const themes = Array.isArray(raw.themes) ? raw.themes.map(clean).filter(Boolean) : []; return [{ id: clean(raw.uuid || subdomain), title: clean(raw.name), organizer: clean(raw.hosted_by) || "Devfolio", type: clean(raw.type || "Hackathon").replace(/^HACKATHON$/i, "Hackathon"), description: "", url: `https://${subdomain}.devfolio.co/`, startDate: devfolioOpeningLabel(registrationStart), endDate: clean(raw.starts_at), deadline: registrationStart, mode: raw.is_online === true ? "Online" : raw.is_online === false ? "Offline" : "", location: clean(raw.city), tags: [...themes, "Upcoming"].join(", ") || "Upcoming", status: "Upcoming", eligibility: "See event page for registration details", logo: clean(settings.logo), featured: clean(raw.devfolio_official) }]; }); return ensureUniqueOpportunityIds(records); }
async function fetchDevfolioPreview() { const apiResponse = await fetch(DEVFOLIO_UPCOMING_API, { method: "POST", headers: { accept: "application/json", "content-type": "application/json", origin: "https://devfolio.co", referer: "https://devfolio.co/hackathons/upcoming", "user-agent": "Coimbatore Events API/1.0" }, body: JSON.stringify({ type: "upcoming", from: 0, size: 100 }), signal: AbortSignal.timeout(30000) }); if (apiResponse.ok) { try { const records = parseDevfolioUpcomingApi(await apiResponse.json()); if (records.length) return { records }; } catch { /* fall through to the reader fallback when a proxy returns non-JSON */ } } const response = await fetch(DEVFOLIO_UPCOMING_READER_URL, { headers: { accept: "text/markdown", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(30000) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return { records: parseDevfolioUpcoming(await response.text()) }; }

const INTERNSHALA_HACKATHONS_URL = "https://internshala.com/competitions/hackathons/";
const INTERNSHALA_MAX_PAGES = 12;
function internshalaDate(value: string) { const match = clean(value).match(/(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})/); if (!match) return ""; const month = MONTH_INDEX[match[2].slice(0, 3).toLowerCase()]; const day = Number(match[1]); const year = Number(match[3]); return month !== undefined && Number.isFinite(day) && Number.isFinite(year) ? new Date(Date.UTC(year, month, day, 23, 59, 59)).toISOString() : ""; }
export function parseInternshalaHackathons(html: string, now = Date.now()) {
  const $ = load(html); const records = $(".box-wrapper-cat").toArray().flatMap(card => { const node = $(card); const titleAnchor = node.find("h2.blog-item-head a").first(); const title = clean(titleAnchor.text()); const href = clean(titleAnchor.attr("href")); const dateLine = clean(node.find(".meta-author-new").first().text()); const deadline = internshalaDate(dateLine); if (!title || !href || !deadline || Date.parse(deadline) <= now) return []; const organizer = clean(node.find(".entry-meta-new span:not(.tag)").first().text()) || "Organizer not listed"; const prize = clean(node.find(".prizetag").first().text()); const logo = clean(node.find(".featured-image img").first().attr("src")); const mode = /online/i.test(dateLine) ? "Online" : /offline|in person/i.test(dateLine) ? "Offline" : ""; const cost = /free/i.test(dateLine) ? "Free" : ""; return [{ id: href, title, organizer, type: "Hackathon", description: dateLine, url: href, startDate: dateLine.match(/\d{1,2}\s+[A-Za-z]+\s+\d{4}/)?.[0] || "", deadline, mode, tags: "Hackathons", prizes: prize, prizePool: prize, logo, status: "Open", eligibility: cost || "See event page for participation details" }]; }); return ensureUniqueOpportunityIds(records);
}
function internshalaPageCount(html: string) { const pages = Array.from(html.matchAll(/\/hackathons\/page\/(\d+)/g), match => Number(match[1])).filter(Number.isFinite); return Math.min(Math.max(...pages, 1), INTERNSHALA_MAX_PAGES); }
async function fetchInternshalaPreview() { const headers = { accept: "text/html,application/xhtml+xml", "user-agent": "Coimbatore Events API/1.0" }; const firstResponse = await fetch(INTERNSHALA_HACKATHONS_URL, { headers, signal: AbortSignal.timeout(30000) }); if (!firstResponse.ok) throw new Error(`HTTP ${firstResponse.status}`); const first = await firstResponse.text(); const pages = internshalaPageCount(first); const rest = await Promise.all(Array.from({ length: pages - 1 }, (_, index) => fetch(`${INTERNSHALA_HACKATHONS_URL}page/${index + 2}/`, { headers, signal: AbortSignal.timeout(30000) }).then(async response => { if (!response.ok) throw new Error(`HTTP ${response.status} on page ${index + 2}`); return await response.text(); }))); return { records: dedupeByCanonicalUrl([first, ...rest].flatMap(page => parseInternshalaHackathons(page))) }; }

async function fetchGenericSite(site: typeof SUPPORTED_SITES[number]) {
  const fetchedAt = new Date().toISOString();
  try {
    await assertSafePublicUrl(site.listingUrl);
    const response = await fetch(site.listingUrl, { headers: { accept: "text/html,application/xhtml+xml", "user-agent": "Coimbatore Events API/1.0" }, signal: AbortSignal.timeout(45000) });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const html = await response.text(); const $ = load(html); const records: Opportunity[] = [];
    $("table tr").each((index, row) => { if (index === 0) return; const cells = $(row).find("th,td").map((_, cell) => clean($(cell).text())).get(); if (!cells.length) return; const link = $(row).find("a").first().attr("href"); records.push(normalizeOpportunity(site.name, site.id, { title: cells[0], description: cells.slice(1).join(" · "), url: link ? new URL(link, site.listingUrl).toString() : site.listingUrl, type: site.category, sourceText: cells.join(" ") })); });
    if (!records.length) $("a").each((_, anchor) => { const title = clean($(anchor).text()); const href = $(anchor).attr("href"); if (!title || title.length < 8 || !href || records.length >= 40) return; const text = clean($(anchor).parent().text()); if (title.toLowerCase() === "learn more" || title.toLowerCase() === "login") return; records.push(normalizeOpportunity(site.name, site.id, { title, description: text, url: new URL(href, site.listingUrl).toString(), type: site.category })); });
    return { site: site.name, siteId: site.id, status: records.length ? "ok" : site.id === "topcoder" ? "blocked" : "no-records", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt, records: ensureUniqueOpportunityIds(records.slice(0, 40)) };
  } catch (error) { const message = error instanceof Error ? error.message : "Unable to fetch source"; const status = classifySourceFetchError(message); return { site: site.name, siteId: site.id, status, access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt, error: message, records: [] }; }
}

export async function opportunitiesApiHandler(_req: Request, res: Response) {
  if (cachedOpportunities && cachedOpportunities.expiresAt > Date.now()) return res.json(cachedOpportunities.payload);
  const results = await Promise.all(SUPPORTED_SITES.map(async site => {
    if (site.id === "devpost") { try { const result = await withSourceTimeout(fetchDevpostPreview(), 25000); return { site: site.name, siteId: site.id, status: result.records.length ? "ok" : "no-records", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, record))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    if (site.id === "kaggle") { try { const result = await withSourceTimeout(fetchKagglePreview(), 50000); return { site: site.name, siteId: site.id, status: result.records.length ? "ok" : "no-records", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, record))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    if (site.id === "unstop") { try { const result = await withSourceTimeout(fetchUnstopPreview(site.listingUrl)); return { site: site.name, siteId: site.id, status: "ok", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, { ...record, url: record.detailUrl || record.registrationUrl }))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    if (site.id === "hack-club") { try { const result = await withSourceTimeout(fetchHackClubPreview(site.listingUrl)); return { site: site.name, siteId: site.id, status: "ok", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, record))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    if (site.id === "hack2skill") { try { const result = await withSourceTimeout(fetchHack2SkillPreview()); return { site: site.name, siteId: site.id, status: result.records.length ? "ok" : "no-records", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, record))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    if (site.id === "reskill") { try { const result = await withSourceTimeout(fetchReskillPreview()); return { site: site.name, siteId: site.id, status: result.records.length ? "ok" : "no-records", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, record))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    if (site.id === "devfolio") { try { const result = await withSourceTimeout(fetchDevfolioPreview()); return { site: site.name, siteId: site.id, status: result.records.length ? "ok" : "no-records", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, record))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    if (site.id === "internshala") { try { const result = await withSourceTimeout(fetchInternshalaPreview()); return { site: site.name, siteId: site.id, status: result.records.length ? "ok" : "no-records", access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(result.records.map(record => normalizeOpportunity(site.name, site.id, record))) }; } catch (error) { return { site: site.name, siteId: site.id, status: classifySourceFetchError(error instanceof Error ? error.message : "Unable to fetch source"), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: error instanceof Error ? error.message : "Unable to fetch source", records: [] }; } }
    return withSourceTimeout(fetchGenericSite(site)).catch(error => { const message = error instanceof Error ? error.message : "Unable to fetch source"; return { site: site.name, siteId: site.id, status: classifySourceFetchError(message), access: site.access, upcomingStatus: site.upcomingStatus, listingUrl: site.listingUrl, fetchedAt: new Date().toISOString(), error: message, records: [] }; });
  }));
  try { const events = await withSourceTimeout(getEvents()); results.push({ site: "KnowAFest Coimbatore", siteId: "knowafest", status: "ok", access: "public-page-adapter", upcomingStatus: "confirmed", listingUrl: "https://www.knowafest.com/explore/city/Coimbatore", fetchedAt: new Date().toISOString(), records: ensureUniqueOpportunityIds(events.map(event => normalizeOpportunity("KnowAFest Coimbatore", "knowafest", { id: event.id, title: event.eventName, organizer: event.organizer, type: event.eventType, startDate: event.startDate, endDate: event.endDate, url: event.eventUrl, location: "Coimbatore, Tamil Nadu, India" }))) }); } catch { results.push({ site: "KnowAFest Coimbatore", siteId: "knowafest", status: "error", access: "public-page-adapter", upcomingStatus: "confirmed", listingUrl: "https://www.knowafest.com/explore/city/Coimbatore", fetchedAt: new Date().toISOString(), records: [] }); }
  const records = results.flatMap(result => result.records.map(record => {
    const sourcePageUrl = record.sourcePageUrl || result.listingUrl;
    const trustInput = { ...record, sourcePageUrl };
    return { ...record, sourcePageUrl, url: record.registrationUrl || record.eventUrl || sourcePageUrl, status: deriveOpportunityStatus(trustInput), dataQuality: opportunityDataQuality(trustInput) };
  })).filter(record => isDefaultUpcoming(record));
  const payload = { generatedAt: new Date().toISOString(), count: records.length, sourceCount: results.length, sources: results, records }; cachedOpportunities = { expiresAt: Date.now() + 2 * 60 * 1000, payload }; return res.json(payload);
}
